name: Prod deploy

on:
  push:
    branches: [ "release/prod" ]
  pull_request:
    branches: [ "release/prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run test
      - run: npm run build
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: dist/
          server-dir: rope-data-sheet/
          log-level: verbose
          
